const img=(id)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;
const projects=[
 {id:1,title:'Villa Moderne',slug:'villa-moderne',categoryId:1,category:'Moderne',shortDescription:'Villa contemporaine ouverte sur le jardin.',description:'Une villa aux lignes contemporaines, ouverte sur le jardin et baignée de lumière. Les volumes épurés associent pierre naturelle, bois et larges baies vitrées.',style:'Moderne',surface:220,landSurface:350,floors:2,bedrooms:4,bathrooms:3,garage:true,location:'France',status:'published',views:1245,coverImage:img('photo-1600585154340-be6161a56a0c'),images:[{id:1,imageUrl:img('photo-1600585154340-be6161a56a0c'),altText:'Villa moderne'}],plans:[],model3dUrl:null},
 {id:2,title:'Maison Contemporaine',slug:'maison-contemporaine',categoryId:2,category:'Contemporain',shortDescription:'Une maison familiale autour d’un patio paysagé.',description:'Une maison fonctionnelle et lumineuse autour d’un séjour traversant et d’un patio paysagé.',style:'Contemporain',surface:180,landSurface:290,floors:1,bedrooms:3,bathrooms:2,garage:false,location:'France',status:'published',views:982,coverImage:img('photo-1600607687939-ce8a6c25118c'),images:[{id:2,imageUrl:img('photo-1600607687939-ce8a6c25118c'),altText:'Maison contemporaine'}],plans:[],model3dUrl:null},
 {id:3,title:'Villa Traditionnelle',slug:'villa-traditionnelle',categoryId:3,category:'Traditionnel',shortDescription:'Une architecture traditionnelle revisitée.',description:'Une interprétation actuelle de la maison traditionnelle avec des matériaux durables et des pièces généreuses.',style:'Traditionnel',surface:250,landSurface:480,floors:2,bedrooms:4,bathrooms:3,garage:true,location:'France',status:'published',views:876,coverImage:img('photo-1600566753086-00f18fb6b3ea'),images:[{id:3,imageUrl:img('photo-1600566753086-00f18fb6b3ea'),altText:'Villa traditionnelle'}],plans:[],model3dUrl:null},
 {id:4,title:'Maison Minimaliste',slug:'maison-minimaliste',categoryId:4,category:'Minimaliste',shortDescription:'La lumière et les proportions à l’essentiel.',description:'Un refuge minimaliste où la lumière, les proportions et les matières font l’essentiel.',style:'Minimaliste',surface:160,landSurface:240,floors:1,bedrooms:3,bathrooms:2,garage:false,location:'France',status:'published',views:654,coverImage:img('photo-1600607687920-4e2a09cf159d'),images:[{id:4,imageUrl:img('photo-1600607687920-4e2a09cf159d'),altText:'Maison minimaliste'}],plans:[],model3dUrl:null},
];
const categories=[{id:1,name:'Moderne',slug:'moderne'},{id:2,name:'Contemporain',slug:'contemporain'},{id:3,name:'Traditionnel',slug:'traditionnel'},{id:4,name:'Minimaliste',slug:'minimaliste'}];
export function demoApi(config){const method=(config.method||'get').toLowerCase(),url=new URL(config.url||'/',location.origin),path=url.pathname.replace(/^\/api/,'').replace(/\/$/,'')||'/',body=typeof config.data==='string'?JSON.parse(config.data||'{}'):config.data||{};
 if(path==='/categories'&&method==='get')return categories;
 if(path.startsWith('/categories/'))return categories.find(c=>c.slug===path.split('/').pop())||null;
 if(path==='/projects'&&method==='get'){const q=url.searchParams,search=(q.get('search')||'').toLowerCase(),category=q.get('category');let rows=projects.filter(p=>p.status==='published'&&(!search||`${p.title} ${p.shortDescription}`.toLowerCase().includes(search))&&(!category||p.category.toLowerCase()===category||String(p.categoryId)===category));const page=Number(q.get('page')||1),limit=Number(q.get('limit')||12);return{projects:rows.slice((page-1)*limit,page*limit),pagination:{page,limit,total:rows.length,totalPages:Math.ceil(rows.length/limit)}}}
 if(path.startsWith('/projects/')){const parts=path.split('/').filter(Boolean),p=projects.find(x=>x.slug===parts[1]||String(x.id)===parts[1]);if(parts.length===3&&parts[2]==='view'){if(p)p.views++;return null}if(parts.length===3&&parts[2]==='images')return p?.images||[];if(parts.length===3&&parts[2]==='plans')return p?.plans||[];return p||null}
 if(path==='/messages'&&method==='post')return{id:Date.now()};
 return undefined;
}
