USE archihome;
INSERT IGNORE INTO categories (name, slug, description) VALUES
('Moderne','moderne','Maisons aux lignes épurées et volumes contemporains.'),
('Contemporain','contemporain','Projets contemporains et lumineux.'),
('Traditionnel','traditionnel','Architecture traditionnelle revisitée.'),
('Minimaliste','minimaliste','Maisons minimalistes et fonctionnelles.');

INSERT IGNORE INTO projects(category_id,title,slug,short_description,description,style,surface,land_surface,floors,bedrooms,bathrooms,garage,location,status,published_at) SELECT id,'Villa Moderne','villa-moderne','Villa contemporaine ouverte sur le jardin.','Une villa aux lignes contemporaines, ouverte sur le jardin et baignée de lumière. Les volumes épurés associent pierre naturelle, bois et larges baies vitrées.','Moderne',220,350,2,4,3,TRUE,'France','published',NOW() FROM categories WHERE slug='moderne';
INSERT IGNORE INTO projects(category_id,title,slug,short_description,description,style,surface,land_surface,floors,bedrooms,bathrooms,garage,location,status,published_at) SELECT id,'Maison Contemporaine','maison-contemporaine','Une maison familiale autour d’un patio paysagé.','Une maison fonctionnelle et lumineuse autour d’un séjour traversant et d’un patio paysagé.','Contemporain',180,290,1,3,2,FALSE,'France','published',NOW() FROM categories WHERE slug='contemporain';
INSERT IGNORE INTO projects(category_id,title,slug,short_description,description,style,surface,land_surface,floors,bedrooms,bathrooms,garage,location,status,published_at) SELECT id,'Villa Traditionnelle','villa-traditionnelle','Une architecture traditionnelle revisitée.','Une interprétation actuelle de la maison traditionnelle avec des matériaux durables et des pièces généreuses.','Traditionnel',250,480,2,4,3,TRUE,'France','published',NOW() FROM categories WHERE slug='traditionnel';
INSERT IGNORE INTO projects(category_id,title,slug,short_description,description,style,surface,land_surface,floors,bedrooms,bathrooms,garage,location,status,published_at) SELECT id,'Maison Minimaliste','maison-minimaliste','La lumière et les proportions à l’essentiel.','Un refuge minimaliste où la lumière, les proportions et les matières font l’essentiel.','Minimaliste',160,240,1,3,2,FALSE,'France','published',NOW() FROM categories WHERE slug='minimaliste';

INSERT INTO project_images(project_id,image_url,alt_text,sort_order,is_cover) SELECT id,'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=82','Villa moderne avec jardin',0,TRUE FROM projects WHERE slug='villa-moderne' AND NOT EXISTS(SELECT 1 FROM project_images WHERE project_id=projects.id);
INSERT INTO project_images(project_id,image_url,alt_text,sort_order,is_cover) SELECT id,'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=82','Maison contemporaine lumineuse',0,TRUE FROM projects WHERE slug='maison-contemporaine' AND NOT EXISTS(SELECT 1 FROM project_images WHERE project_id=projects.id);
INSERT INTO project_images(project_id,image_url,alt_text,sort_order,is_cover) SELECT id,'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=82','Villa traditionnelle',0,TRUE FROM projects WHERE slug='villa-traditionnelle' AND NOT EXISTS(SELECT 1 FROM project_images WHERE project_id=projects.id);
INSERT INTO project_images(project_id,image_url,alt_text,sort_order,is_cover) SELECT id,'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=82','Maison minimaliste',0,TRUE FROM projects WHERE slug='maison-minimaliste' AND NOT EXISTS(SELECT 1 FROM project_images WHERE project_id=projects.id);
