import { Router } from 'express';
const router=Router();
const categories=[{id:1,name:'Moderne',slug:'moderne',description:'Architecture contemporaine',isActive:1},{id:2,name:'Contemporain',slug:'contemporain',description:'Projets lumineux',isActive:1},{id:3,name:'Traditionnel',slug:'traditionnel',description:'Tradition revisitée',isActive:1},{id:4,name:'Minimaliste',slug:'minimaliste',description:'Volumes essentiels',isActive:1}];
const photo=id=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=82`;
const projects=[
 {id:1,title:'Villa Moderne',slug:'villa-moderne',categoryId:1,category:'Moderne',shortDescription:'Villa contemporaine ouverte sur le jardin.',description:'Une villa aux lignes contemporaines, ouverte sur le jardin et baignée de lumière.',style:'Moderne',surface:220,landSurface:350,floors:2,bedrooms:4,bathrooms:3,garage:true,location:'France',status:'published',views:1245,coverImage:photo('photo-1600585154340-be6161a56a0c'),images:[],plans:[],model3dUrl:null,createdAt:'2026-04-12'},
 {id:2,title:'Maison Contemporaine',slug:'maison-contemporaine',categoryId:2,category:'Contemporain',shortDescription:'Une maison familiale autour d’un patio paysagé.',description:'Une maison fonctionnelle et lumineuse autour d’un séjour traversant.',style:'Contemporain',surface:180,landSurface:290,floors:1,bedrooms:3,bathrooms:2,garage:false,location:'France',status:'published',views:982,coverImage:photo('photo-1600607687939-ce8a6c25118c'),images:[],plans:[],model3dUrl:null,createdAt:'2026-04-10'},
 {id:3,title:'Villa Traditionnelle',slug:'villa-traditionnelle',categoryId:3,category:'Traditionnel',shortDescription:'Une architecture traditionnelle revisitée.',description:'Une interprétation actuelle avec des matériaux durables.',style:'Traditionnel',surface:250,landSurface:480,floors:2,bedrooms:4,bathrooms:3,garage:true,location:'France',status:'published',views:876,coverImage:photo('photo-1600566753086-00f18fb6b3ea'),images:[],plans:[],model3dUrl:null,createdAt:'2026-04-08'},
 {id:4,title:'Maison Minimaliste',slug:'maison-minimaliste',categoryId:4,category:'Minimaliste',shortDescription:'La lumière et les proportions à l’essentiel.',description:'Un refuge minimaliste où la lumière et les matières font l’essentiel.',style:'Minimaliste',surface:160,landSurface:240,floors:1,bedrooms:3,bathrooms:2,garage:false,location:'France',status:'published',views:654,coverImage:photo('photo-1600607687920-4e2a09cf159d'),images:[],plans:[],model3dUrl:null,createdAt:'2026-04-05'}
];
const messages=[{id:1,name:'Marie Laurent',email:'marie@example.com',subject:'Projet Villa Moderne',message:'Bonjour, je souhaite en savoir davantage sur ce projet.',status:'unread',createdAt:new Date().toISOString()}];
const admin={id:1,name:'Admin Démo',email:'admin@archirani.local',role:'super_admin'};const siteSettings={site_name:'Archirani',company_email:'',company_phone:'',company_address:'',linkedin_url:'',instagram_url:'',facebook_url:''};
const ok=(res,data,status=200)=>res.status(status).json({success:true,message:'Local demo data',data});
router.get('/health',(req,res)=>ok(res,{status:'demo'}));router.get('/settings',(req,res)=>ok(res,{siteName:siteSettings.site_name||'Archirani',companyEmail:siteSettings.company_email,companyPhone:siteSettings.company_phone,companyAddress:siteSettings.company_address,linkedinUrl:siteSettings.linkedin_url,instagramUrl:siteSettings.instagram_url,facebookUrl:siteSettings.facebook_url}));
router.get('/auth/me',(req,res)=>ok(res,{admin}));router.get('/auth/setup-status',(req,res)=>ok(res,{required:false}));router.post('/auth/setup',(req,res)=>ok(res,{admin},201));router.post('/auth/login',(req,res)=>ok(res,{admin}));router.post('/auth/logout',(req,res)=>ok(res,null));router.put('/auth/password',(req,res)=>ok(res,null));
router.get('/categories',(req,res)=>ok(res,categories.filter(c=>c.isActive)));router.get('/categories/:slug',(req,res)=>ok(res,categories.find(c=>c.slug===req.params.slug)||null));
router.get('/projects',(req,res)=>{const q=req.query;let rows=projects.filter(p=>p.status==='published'&&(!q.search||`${p.title} ${p.shortDescription}`.toLowerCase().includes(String(q.search).toLowerCase()))&&(!q.category||p.category.toLowerCase()===String(q.category).toLowerCase()));const page=Number(q.page)||1,limit=Math.min(48,Number(q.limit)||12);if(q.sort==='popular')rows=[...rows].sort((a,b)=>b.views-a.views);return ok(res,{projects:rows.slice((page-1)*limit,page*limit),pagination:{page,limit,total:rows.length,totalPages:Math.ceil(rows.length/limit)}})});
router.get('/projects/:slug',(req,res)=>ok(res,projects.find(p=>p.status==='published'&&(p.slug===req.params.slug||String(p.id)===req.params.slug))||null));router.get('/projects/:id/images',(req,res)=>ok(res,projects.find(p=>String(p.id)===req.params.id)?.images||[]));router.get('/projects/:id/plans',(req,res)=>ok(res,projects.find(p=>String(p.id)===req.params.id)?.plans||[]));router.post('/projects/:id/view',(req,res)=>{const p=projects.find(x=>x.id===Number(req.params.id));if(p)p.views++;return ok(res,null)});router.post('/messages',(req,res)=>{const id=Date.now();messages.unshift({id,...req.body,status:'unread',createdAt:new Date().toISOString()});return ok(res,{id},201)});
router.get('/admin/dashboard/stats',(req,res)=>ok(res,{total:12,published:10,drafts:2,archived:0,views:5432,messages:messages.length,unread:messages.filter(m=>m.status==='unread').length,categories:categories.length}));router.get('/admin/dashboard/recent-projects',(req,res)=>ok(res,projects.slice(0,8)));router.get('/admin/dashboard/popular-projects',(req,res)=>ok(res,[...projects].sort((a,b)=>b.views-a.views).slice(0,8)));router.get('/admin/dashboard/views',(req,res)=>ok(res,Array.from({length:7},(_,i)=>({date:new Date(Date.now()-(6-i)*86400000).toISOString().slice(0,10),total:[18,26,21,38,29,44,35][i]}))));
router.get('/admin/projects',(req,res)=>ok(res,{projects,pagination:{page:1,limit:100,total:projects.length,totalPages:1}}));router.get('/admin/projects/:id',(req,res)=>ok(res,projects.find(p=>p.id===Number(req.params.id))||null));router.get('/admin/categories',(req,res)=>ok(res,categories));router.get('/admin/messages',(req,res)=>ok(res,messages));router.get('/admin/settings',(req,res)=>ok(res,siteSettings));
router.post('/admin/projects',(req,res)=>{const id=Math.max(...projects.map(p=>p.id))+1,p={...req.body,id,slug:String(req.body.title||'projet').toLowerCase().replace(/\s+/g,'-'),category:categories.find(c=>c.id===Number(req.body.categoryId))?.name,status:req.body.status||'draft',views:0,images:[],plans:[],model3dUrl:null};projects.unshift(p);return ok(res,{id},201)});router.put('/admin/projects/:id',(req,res)=>{const p=projects.find(x=>x.id===Number(req.params.id));if(p)Object.assign(p,req.body);return ok(res,p||null)});router.delete('/admin/projects/:id',(req,res)=>{const i=projects.findIndex(p=>p.id===Number(req.params.id));if(i>=0)projects.splice(i,1);return ok(res,null)});
for(const [action,status] of [['publish','published'],['unpublish','draft'],['archive','archived']])router.patch(`/admin/projects/:id/${action}`,(req,res)=>{const p=projects.find(x=>x.id===Number(req.params.id));if(p)p.status=status;return ok(res,{id:p?.id,status})});
router.post('/admin/projects/:id/model',(req,res)=>ok(res,{model3dUrl:null},201));router.delete('/admin/projects/:id/model',(req,res)=>ok(res,null));router.post('/admin/projects/:id/images',(req,res)=>ok(res,[],201));router.post('/admin/projects/:id/plans',(req,res)=>ok(res,[],201));router.put('/admin/images/:id',(req,res)=>ok(res,null));router.delete('/admin/images/:id',(req,res)=>ok(res,null));router.patch('/admin/projects/:id/images/reorder',(req,res)=>ok(res,null));router.put('/admin/plans/:id',(req,res)=>ok(res,null));router.delete('/admin/plans/:id',(req,res)=>ok(res,null));
router.post('/admin/categories',(req,res)=>{const id=Math.max(...categories.map(c=>c.id))+1,c={...req.body,id,isActive:1};categories.push(c);return ok(res,{id},201)});router.put('/admin/categories/:id',(req,res)=>{const c=categories.find(x=>x.id===Number(req.params.id));if(c)Object.assign(c,req.body);return ok(res,null)});router.delete('/admin/categories/:id',(req,res)=>{const c=categories.find(x=>x.id===Number(req.params.id));if(c)c.isActive=0;return ok(res,null)});
router.get('/admin/messages/:id',(req,res)=>ok(res,messages.find(m=>m.id===Number(req.params.id))||null));for(const state of ['read','unread','archive'])router.patch(`/admin/messages/:id/${state}`,(req,res)=>{const m=messages.find(x=>x.id===Number(req.params.id));if(m)m.status=state==='archive'?'archived':state;return ok(res,null)});router.delete('/admin/messages/:id',(req,res)=>ok(res,null));router.put('/admin/settings',(req,res)=>{for(const k of ['site_name','company_email','company_phone','company_address','linkedin_url','instagram_url','facebook_url'])if(typeof req.body?.[k]==='string')siteSettings[k]=req.body[k];return ok(res,null)});
router.use((req,res)=>res.status(404).json({success:false,message:'Demo endpoint not found',code:'NOT_FOUND'}));
export default router;
