const photo=(id)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=600&q=75`;
let projects=[
 {id:1,title:'Villa Moderne',slug:'villa-moderne',categoryId:1,category:'Moderne',shortDescription:'Villa contemporaine ouverte sur le jardin.',description:'Une villa aux lignes contemporaines, ouverte sur le jardin et baignée de lumière.',style:'Moderne',surface:220,landSurface:350,floors:2,bedrooms:4,bathrooms:3,garage:true,location:'France',status:'published',views:1245,coverImage:photo('photo-1600585154340-be6161a56a0c'),images:[],plans:[],model3dUrl:null,createdAt:'2026-04-12'},
 {id:2,title:'Maison Contemporaine',slug:'maison-contemporaine',categoryId:2,category:'Contemporain',shortDescription:'Maison familiale et patio paysagé.',description:'Une maison fonctionnelle et lumineuse autour d’un séjour traversant.',style:'Contemporain',surface:180,landSurface:290,floors:1,bedrooms:3,bathrooms:2,garage:false,location:'France',status:'published',views:982,coverImage:photo('photo-1600607687939-ce8a6c25118c'),images:[],plans:[],model3dUrl:null,createdAt:'2026-04-10'},
 {id:3,title:'Villa Traditionnelle',slug:'villa-traditionnelle',categoryId:3,category:'Traditionnel',shortDescription:'Une architecture traditionnelle revisitée.',description:'Une interprétation actuelle avec des matériaux durables.',style:'Traditionnel',surface:250,landSurface:480,floors:2,bedrooms:4,bathrooms:3,garage:true,location:'France',status:'published',views:876,coverImage:photo('photo-1600566753086-00f18fb6b3ea'),images:[],plans:[],model3dUrl:null,createdAt:'2026-04-08'},
 {id:4,title:'Maison Minimaliste',slug:'maison-minimaliste',categoryId:4,category:'Minimaliste',shortDescription:'La lumière et les proportions à l’essentiel.',description:'Un refuge minimaliste où la lumière et les matières font l’essentiel.',style:'Minimaliste',surface:160,landSurface:240,floors:1,bedrooms:3,bathrooms:2,garage:false,location:'France',status:'draft',views:654,coverImage:photo('photo-1600607687920-4e2a09cf159d'),images:[],plans:[],model3dUrl:null,createdAt:'2026-04-05'},
];
let categories=[{id:1,name:'Moderne',slug:'moderne',description:'Maisons modernes',isActive:1},{id:2,name:'Contemporain',slug:'contemporain',description:'Projets contemporains',isActive:1},{id:3,name:'Traditionnel',slug:'traditionnel',description:'Architecture traditionnelle',isActive:1},{id:4,name:'Minimaliste',slug:'minimaliste',description:'Architecture minimaliste',isActive:1}];
const messages=[{id:1,name:'Marie Laurent',email:'marie@example.com',phone:'',subject:'Projet Villa Moderne',message:'Bonjour, je souhaite en savoir davantage sur ce projet. Merci !',status:'unread',createdAt:new Date().toISOString()},{id:2,name:'Paul Durand',email:'paul@example.com',phone:'',subject:'Demande de plans',message:'Pourriez-vous me transmettre les plans de la maison contemporaine ?',status:'read',createdAt:new Date(Date.now()-86400000).toISOString()}];
let siteSettings={site_name:'Archirani',company_email:'',company_phone:'',company_address:'',linkedin_url:'',instagram_url:'',facebook_url:''};
export function demoApi(config){const method=(config.method||'get').toLowerCase(),url=new URL(config.url||'/',location.origin),path=url.pathname.replace(/^\/api/,'').replace(/\/$/,'')||'/',body=typeof config.data==='string'?JSON.parse(config.data||'{}'):config.data||{},admin={id:1,name:'Admin Démo',email:'admin@archirani.local',role:'super_admin'};
 if(path==='/auth/me'||path==='/auth/login')return{admin};if(path==='/auth/logout')return null;if(path==='/auth/password')return null;
 if(path==='/admin/dashboard/stats')return{total:12,published:10,drafts:2,archived:0,views:5432,messages:messages.length,unread:messages.filter(m=>m.status==='unread').length,categories:categories.length};
 if(path==='/admin/dashboard/recent-projects')return projects.slice(0,8);if(path==='/admin/dashboard/popular-projects')return [...projects].sort((a,b)=>b.views-a.views).slice(0,8);if(path==='/admin/dashboard/views')return Array.from({length:7},(_,i)=>({date:new Date(Date.now()-(6-i)*86400000).toISOString().slice(0,10),total:[18,26,21,38,29,44,35][i]}));
 if(path==='/admin/projects'&&method==='get'){const limit=Number(url.searchParams.get('limit')||50),page=Number(url.searchParams.get('page')||1);return{projects:projects.slice((page-1)*limit,page*limit),pagination:{page,limit,total:projects.length,totalPages:Math.ceil(projects.length/limit)}}}
 if(path==='/admin/projects'&&method==='post'){const id=Math.max(0,...projects.map(x=>x.id))+1,p={...body,id,slug:(body.slug||body.title||`projet-${id}`).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),category:categories.find(c=>c.id===Number(body.categoryId))?.name||'Moderne',status:body.status||'draft',views:0,createdAt:new Date().toISOString(),coverImage:'',images:[],plans:[],model3dUrl:null};projects=[p,...projects];return{id}}
 const detail=path.match(/^\/admin\/projects\/(\d+)$/);if(detail){const id=Number(detail[1]);if(method==='get')return projects.find(p=>p.id===id)||null;if(method==='put'){projects=projects.map(p=>p.id===id?{...p,...body}:p);return projects.find(p=>p.id===id)}if(method==='delete'){projects=projects.filter(p=>p.id!==id);return null}}
 const action=path.match(/^\/admin\/projects\/(\d+)\/(publish|unpublish|archive|model|images|plans)$/);if(action){const id=Number(action[1]),act=action[2],p=projects.find(x=>x.id===id);if(act==='publish'||act==='unpublish'||act==='archive'){const status=act==='publish'?'published':act==='archive'?'archived':'draft';projects=projects.map(x=>x.id===id?{...x,status}:x);return{id,status}}if(act==='model'&&method==='post'&&p){p.model3dUrl='https://example.invalid/demo-model.glb';return{model3dUrl:p.model3dUrl}}if(act==='model'&&method==='delete'&&p){p.model3dUrl=null;return null}if(act==='images'&&method==='post'&&p)return p.images;if(act==='plans'&&method==='post'&&p)return p.plans}
 if(path==='/admin/categories'&&method==='get')return categories;if(path==='/admin/categories'&&method==='post'){const id=Math.max(0,...categories.map(c=>c.id))+1,c={id,...body,slug:(body.name||'category').toLowerCase().replace(/\s+/g,'-'),isActive:1};categories=[...categories,c];return{id}}
 const category=path.match(/^\/admin\/categories\/(\d+)$/);if(category){const id=Number(category[1]);if(method==='put'){categories=categories.map(c=>c.id===id?{...c,...body,slug:(body.name||c.name).toLowerCase().replace(/\s+/g,'-')}:c);return null}if(method==='delete'){categories=categories.map(c=>c.id===id?{...c,isActive:0}:c);return null}}
 if(path==='/admin/messages'&&method==='get')return messages.filter(m=>!url.searchParams.get('status')||m.status===url.searchParams.get('status'));const message=path.match(/^\/admin\/messages\/(\d+)(?:\/(read|unread|archive))?$/);if(message){const id=Number(message[1]),action=message[2],m=messages.find(x=>x.id===id);if(action&&m){m.status=action==='archive'?'archived':action;return null}if(method==='delete'){const i=messages.findIndex(x=>x.id===id);if(i>=0)messages.splice(i,1);return null}return m||null}
 if(path==='/admin/settings'&&method==='get')return siteSettings;if(path==='/admin/settings'&&method==='put'){siteSettings={...siteSettings,...body};return null;}
 if(path.startsWith('/admin/images/')||path.startsWith('/admin/plans/'))return null;
 return undefined;
}
